  - name: Restart bind9
    service:
      name: bind9
      state: restarted
    listen: "restart bind9 service"

  - name: Restart rndc reload
    ansible.builtin.command:
      cmd: rndc reload
    listen: "rndc reload"

